### ISSUE TITLE
Questions about Prototype 1

### ISSUE THREAD

**Issue by HL232** [HL232/LEDLight_FundEngDesign#3]
@mlp6 
Hi Dr. Palmeri, I created a working prototype 1.0 for this device a few weeks back. You can see a video of it in my `Testing` folder. I had a few quick questions before adding some stuff for Milestone 3:

1. I power my Arduino board with the 9V battery, and I'm powering the LED with the built in 5V Arduino pin. I anticipate a few problems with this. The voltage regulator of the 5V pin draws a lot of current, so battery life won't be great, and if the 5V regulator isn't reliable, then there's no guarantee that the LED is connected to 5V at all times. With only one battery, there's no way to power the Arduino and attach 9V to the breadboard is there? Alternatively, I was thinking about connecting a voltage regulator to the 5V pin, and regulating the voltage down to like 3V, and using that 3V to power the LED. Thoughts?

2. I forgot about `switch` statements, so I'll change my Arduino code. It works, but it's like the equivalent of screwing in a nail with a hammer.

**Comment by mlp6** [comment]
I don't follow why you cannot attach the battery to two things... can you expand on your concern?

**Comment by HL232** [comment]
Ah, I did a little research. I didn't realize the VIN pin on the Arduino can be used to access the external power source directly. The VIN pin would be the unregulated 9V power supply from the battery. That'll work better. I'll change my schematic based on that
