### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by HL232** [HL232/LEDLight_FundEngDesign#5]
I have added the Altium files for my milestone 4 in the Electronics folder

Note: I built my PCB schematic on top of an existing Arduino Uno Shield Schematic. The original schematic can be found here. https://forum.arduino.cc/index.php?topic=115446.0

TO DO: The connectors on the board are female. What I can do is instead of soldering on the female connectors, I'll just leave the holes and solder on male connecters instead so that it attaches to the top of the Arudino UNO.... (Or I could try to figure out how to replace the female connectors on Altium...)

I need to figure out how to make the button and LED detachable so that they stick out of the housing at the end.

I think I may have mixed surface mount and thru hole parts

I did not use the specific parts, I used the parts in the generic miscellaneous built in Altium library.

**Comment by brinnaebent** [comment]
Schematic-connections are good, you don't have any connections for IOH, AD, ICSP (are these just random headers you are using? please check)
PCB- routes are fine. 
Why didn't you use a polygon pour instead of small GND planes? These will work but a pour would simplify your routes.
