### ISSUE TITLE
ECAD Questions

### ISSUE THREAD

**Issue by HL232** [HL232/LEDLight_FundEngDesign#7]
Hi everyone, 

I updated my Altium PCB since Milestone 5. I still had a few questions about it.

 - I added a copper polygon pour area as GND over the entire PCB. Matt and Dr. Palmeri are printing the boards by _removing_ the areas without copper right? So this should make the process easier? 
 - I set clearance to be 20mils instead of 10 mils, this is the area between the connection "wires" and the copper pour right?
 - I think some of my components are mixed up. VR1, VR2, R1, R2, and D3 (which are the voltage regulators, resistors, and LED respectively) appear without pin holes. While everything else does have pin holes. So some of my parts are surface mount, and some of the parts are thru hole. Since Matt is drilling everything by hand, should I try to replace all the thru hole parts with surface mount parts?

Other than that, let me know if you have any other feedback, thanks! No rush, have a great Thanksgiving!

**Comment by sphaerobolus** [comment]
Our process is subtractive, yes. The more copper you leave on the board, the better. 

Yep, your clearance looks good. 

More SMT parts does mean fewer holes drilled. That said, I'm really quick at drilling holes so this isn't a huge benefit. Further, I don't have SMT voltage regulators. IF you keep using the voltage regulators (more on this later), you might want to switch to TO-220 or TO-92 cases. 

Has someone reviewed this? I am dubious of your zener diodes as placed. I'm not sure you need either voltage regulator if you're using the Uno.
