### ISSUE TITLE
One more change to PCB

### ISSUE THREAD

**Issue by HL232** [HL232/LEDLight_FundEngDesign#8]
Hi Dr. Palmeri, Hi Matt, 

Dr. Palmeri said you guys were printing the PCBs on Monday. I need to add one thing in the morning, so please hold off on mine.

**Comment by mlp6** [comment]
Small nitpick on the schematic: keep connection lines parallel/perpendicular to each other (just aids readability of the schematic).

**Comment by HL232** [comment]
Got it! I've uploaded my final PCB to the Electronics folder. 

Also, I had to rename the Altium files a few times, so there are like a billion altium files on github, which totally defeats the purpose of version control. I'm sorry I've disappointed you Dr. Palmeri @mlp6
